### ISSUE TITLE
Learn is not completing although tests passed

### ISSUE THREAD

**Issue by ChristopherBlack22** [learn-co-curriculum/react-events-in-detail-lab#28] opened 2022-01-08 01:17 UTC
### Canvas Link

https://learning.flatironschool.com/courses/1883/assignments/125694?module_item_id=259619

### Concern

All tests are marked as passed but terminal stalls thereby no posting a completed lab.

**Comment by ihollander** [comment] 2022-01-13 15:59
Hi @ChristopherBlack22 , I wasn't able to reproduce this issue on this lesson, so I'm closing this issue. One thing to try when the tests are stalling is to add the `--exit` flag to the test script to force the tests to exit when complete. The full command looks like this:

```
mocha --timeout 5000 -R mocha-multi --reporter-options spec=-,json=.results.json --exit
```

**Closed as completed by ihollander** 2022-01-13 15:59 UTC
Labels: se curriculum
